// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/providers/Provider";
import { ToasterProvider } from "@/providers/ToasterProvider";
import { SocketProvider } from "@/contexts/SocketContext";
import { AuthGuard } from "@/components/ui/AuthQuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

       <ReduxProvider>
      <SocketProvider>
        <AuthGuard>
        {children}
        </AuthGuard>
      </SocketProvider>
    </ReduxProvider>
      </body>
    </html>
  );
}
