// // app/login/layout.tsx (LoginLayout)
// // app/layout.tsx
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "@/app/global.css";
// import "../../globals.css";

// import { ReduxProvider } from "@/providers/Provider";
// import { ToasterProvider } from "@/providers/ToasterProvider";
// import { SocketProvider } from "@/contexts/SocketContext";
// import Footer from "@/components/ui/Footer";




// import { AuthGuard } from "@/components/ui/AuthQuard";




// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Travel App",
//   description: "Generated by create next app",
// };

// export default function LoginLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
  
//   return (
    
//       <div
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <ReduxProvider>
//           <SocketProvider>
//             <AuthGuard>
//              {children}
//              </AuthGuard>
//           </SocketProvider>
//         </ReduxProvider>
//       </div>
    
//   );
// }


// app/(Auth)/login/layout.tsx
"use client";

// import { ReduxProvider } from "@/providers/Provider";
// import { ToasterProvider } from "@/providers/ToasterProvider";
// import { SocketProvider } from "@/contexts/SocketContext";

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
        {children}
      </>
  );
}
